name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  schedule:
    - [cite_start]cron: '30 12 * * 3'  # Задание 2: Среда 12:30 [cite: 742]
    - [cite_start]cron: '0 22 * * 5'   # Задание 2: Пятница 22:00 [cite: 742]

jobs:
  build:
    strategy:
      matrix:
        [cite_start]os: [ubuntu-latest, windows-latest, macos-latest] # Задание 3: Платформы [cite: 744]
        [cite_start]java: [11, 13, 17] # Задание 3: Версии Java [cite: 744]
    [cite_start]runs-on: ${{ matrix.os }} # Использование ОС из матрицы [cite: 711, 730]
    
    steps:
      - name: Checkout code
        [cite_start]uses: actions/checkout@v4 # Шаг скачивания кода [cite: 393, 715]
        
      - name: Set up JDK
        [cite_start]uses: actions/setup-java@v4 # Установка Java [cite: 395, 719]
        with:
          [cite_start]java-version: ${{ matrix.java }} # Берем версию из матрицы [cite: 732]
          [cite_start]distribution: 'temurin' [cite: 398]
          
      - name: Build with Gradle
        [cite_start]run: ./gradlew build # Задание 1: Сборка и тесты [cite: 403, 740]
